tidyverse/stringr

R/word.r

This bug causes warnings if options(warnPartialMatchArgs=TRUE).

Use full arg name for rep(length.out=...)

---

.travis.yml
tests/testthat/test-wrap.r

Hadley, I think I now have a fix for #68. Anyway, as stringr and stringi are now so tightly connected with each other, what about travis-testing stringr against the github version of stringi? I updated `.travis.yml` accordingly for that.

Update travis conf

---

R/interp.R
man/str_interp.Rd
tests/testthat/test-interp.r

This update does two things: 
1. `str_interp` would fail when no placeholders were found in the input string. This is fixed.
2. Added a suggested feature that makes it easier to break a long single-line string in multiple lines of source code without needing to use e.g  `paste`. Instead if the input string is a formula, hyphens (dashes) can be used to concatenate long strings: 
```R
max_char <- 80
str_interp(~"This particular line is so long that it is hard to write "-
"without breaking the ${max_char}-char barrier!")
```
Here `str_interp` uses an internal utility function `unwrap_string_formula` which will recognize `-` as a hyphen (and not as a minus).

Bugfix + small feature

---

NEWS.md
R/modifiers.r
man/modifiers.Rd
tests/testthat/test-split.r

This is a resubmission of [this PR](https://github.com/hadley/stringr/pull/58/).

Fix sentence splitting

---

tests/testthat/test-match.r
tests/testthat/test-pad.r
tests/testthat/test-word.r

This fixes all the matches I spotted (and adds an extra test, so that we see partial matches in `word` here instead of in dependencies).
There's also some wrapping code that sets and unsets options, so this doesn't immediately arise again -- that should probably move into `testthat`.

Fix existing partial matches in stringr.

---

R/detect.r

Hello,
Minor doc improvement. I always forget what `str_subset()` is called, and end up looking at the docs for `str_detect()` first when I want it, then when it's not there I end up clicking randomly through all the `str_*` functions till I find the one I'm looking for.

@seealso link to str_subset() from str_detect()

---

R/interp.R

Improves life for those of us living the `warnPartialMatch` lifestyle (https://github.com/r-lib/usethis/issues/64)

Eliminate a partial arg match

---

vignettes/stringr.Rmd

edited some minor phrasing in `vignettes/stringr.Rmd`. More importantly, there is a typo in L42 that gave the wrong function (`sub_str()` instead of `str_sub()`)

Spelling and grammar

---

R/interp.R

I spent quite a bit of time trying to make str_interp work like tidyverse/glue_data ... my logic was "tidyverse string stuff is in stringr, str_interp sounds right." So just as tidyverse/glue points to str_interp as an option, this points back (I hope, I'm afraid my rdoc is very weak).

Add link to tidyverse/glue

---

vignettes/regular-expressions.Rmd

Fixed typo that `[\^]` matches `^` and not `\`. Also changed order to be consistent with presentation in regexp.
Is it worth mentioning here that no backslash is needed if `-` is the first character or if `^` is not the first character in the class? In other words `[\^\-]` is equivalent to `[-^]`. (I guess not, it is easier to just learn the rules as escape both inside the `[]`.)

Fix typo in regular expressions vignette

---

R/modifiers.r
man/modifiers.Rd

I assumed `str_split(x, boundary("line_break"))` meant "split `x` on any kind of line-break character".  I was wrong! 
Here are docs I hope are helpful to other people; let me know if you'd like me to change anything.

Add detail to boundary() documentation

---

R/c.r
R/glue.R
man/str_c.Rd
vignettes/releases/stringr-1.2.0.Rmd

- There is no `glue::data`. The correct inheritance should be from `glue::glue_data`, which is already being passed on L39.
- Spelling typo in release 1.2.0 article. `pkgdown` needs to be run by a maintainer for the tidyverse website to be updated.
- Reflowed comment for `str_c` description to trigger a travis build, which now passes all checks

Clean roxygen doc in str_glue and vignette

---

R/trunc.R
tests/testthat/test-trunc.r

Fixes #203.
With the NA logic fix to str_trunc 2 months ago, "&&" was used instead of "&", causing str_trunc to only work on the first element of the vector.
I added a test as well, but nothing in the NEWS since this change wasn't ever released.

Fixed unexpected behavior of str_trunc

---

R/view.R

in the absence of htmlwidgets
To fix #263

Add requireNamespace so str_view() fails more gracefully 

---

R/detect.r
man/str_starts.Rd

* Correct spelling of "pineapple" in example for `str_starts()` and `str_ends()`.

🍍 Fix spelling on pineapple in example.

---

vignettes/from-base.Rmd

Second argument to `str_dup` should match second
argument to `strrep` (both are `n` - number of times
to repeat).

Fix typo in "from base" vignette

---

R/sub.r
man/str_sub.Rd

This PR fixes a minor typo in the `str_sub` examples, both in the .R and .Rd files

Fix typo: colum -> column

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION

dev glue has a fix for the problem cropping up in stringr's CI where knitr fails to install
More detail is here: https://github.com/tidyverse/glue/pull/254
stringr is basically a bystander here, though stringr's `importFrom(glue,glue)` is part of the story

Fix knitr installation on r-devel

---

DESCRIPTION

glue 1.6.1 is on CRAN now
Prior to this little maneuver, stringr's minimum version of glue was 1.2.0. And as far as runtime is concerned, I have no reason to believe stringr needs glue 1.6.1.
glue 1.6.1 just addresses a weird knitr installation edge case that affected glue 1.5.1 and 1.6.0 and has only been seen in CI for stringr. So if you don't want to *force* glue to be updated, you can probably go back to the way it was before.

Don't need dev glue anymore

---

R/view.R
tests/testthat/_snaps/view.md

In 1.5.0, str_view() was improved and as a result str_view_all() [was made redundant and was deprecated.](https://www.tidyverse.org/blog/2022/12/stringr-1-5-0/#str_view)  However, the deprecation warning that is displayed when str_view_all() is called states that str_view() is deprecated and that str_view_all() should be used. This change corrects the warning to say that str_view_all() is deprecated and that str_view() should be used. Fixes issue #488.

Fix str_view_all() deprecation warning

---

R/split.R
man/str_split.Rd

Fix typo in split.R

---

NEWS.md
R/trunc.R
tests/testthat/test-trunc.R

Fix #512 .
This is a pull request similar to #513 .
#512 is caused by the boundary cases of `stringi::stri_sub()` when getting the end of a string.
https://github.com/gagolews/stringi/issues/494
I modified the code to avoid the boundary cases, i.e., `from` is always a positive number, and added tests.
I think this proposal can fix the bug with simpler code than #513 .

Fix bug in `str_trunc()` with simpler code

---

README.Rmd
README.md
_pkgdown.yml

- This pull request updates r4ds(<https://r4ds.had.co.nz/>) to r4ds 2e (https://r4ds.hadley.nz/) on the package website.
- **README.md** is updated by running `devtools::build_readme()`.

Update r4ds url

---

R/split.R
man/str_split.Rd

Spelling mistake : correction of the function name from "str_split1" to "str_split_1" in the documentation (split.R file)

Fix spelling mistake in split.R

---

vignettes/from-base.Rmd

Fix warning by `dplyr::across()` about missing `.cols` arg.
Currently, there's unwanted warning output included in the [rendered vignette](https://stringr.tidyverse.org/articles/from-base.html#overall-differences). This PR fixes this.

Fix warning in vignette

---

NAMESPACE
NEWS.md
R/modifiers.R
tests/testthat/test-modifiers.R

closes #529
copy of [.stringr_pattern with simple test added for both

define [[.stringr_pattern

---

po/R-es.po

Part of https://github.com/tidyverse/stringr/issues/556
#: replace.R:209
#: split.R:122
#: utils.R:26
about _input_ translation: [Translation (or not) of technical terms in Spanish.](https://github.com/cienciadedatos/documentacion-traduccion-r4ds/blob/master/orientaciones-traduccion.md#ii-traducci%C3%B3n-o-no-de-t%C3%A9rminos-t%C3%A9cnicos)

translate error messages ES:

---

po/R-es.po

Translated to Spanish error messages:
#: detect.R:141
#: interp.R:105
#: interp.R:176
#: match.R:54 match.R:68
#: modifiers.R:216
#: replace.R:208
#: replace.R:226
#: replace.R:220
#: trunc.R:32
#: utils.R:23
The rest was submitted at https://github.com/tidyverse/stringr/pull/565

Translated part of error messages to spanish - Fixes #556

---

tests/testthat/_snaps/conv.md
tests/testthat/_snaps/equal.md
tests/testthat/_snaps/flatten.md
tests/testthat/_snaps/match.md
tests/testthat/test-conv.R
tests/testthat/test-equal.R
tests/testthat/test-flatten.R
tests/testthat/test-match.R

Convert expect_error() to expect_snapshot()

---

R/count.R
R/detect.R
R/extract.R
R/locate.R
R/replace.R
R/split.R
man/str_count.Rd
man/str_detect.Rd
man/str_extract.Rd
man/str_locate.Rd
man/str_remove.Rd
man/str_replace.Rd
man/str_split.Rd
man/str_subset.Rd
man/str_view.Rd
man/str_which.Rd

Fixes #508
Co-authored by: @RobLBaker

Fix documentation that implies pattern argument can be empty

---

NEWS.md
R/modifiers.R
tests/testthat/_snaps/modifiers.md
tests/testthat/_snaps/split.md
tests/testthat/test-modifiers.R

Make type.character error for NA_character_

---

NEWS.md
R/dup.R
man/str_dup.Rd
tests/testthat/_snaps/dup.md
tests/testthat/test-dup.R

closes #487
Adds a sep argument to str_dup. Becasue this is not supported by stri_dup, do separately and use lapply to go through strings.

add sep argument to str_dup

---

R/match.R
man/str_match.Rd

Hi `stringr` maintainers 👋
I've noticed a simple typo in the description of the function but haven't run roxygen on it.

Fix typo in code description

---

DESCRIPTION
R/glue.R
R/replace.R
README.Rmd
README.md
data-raw/samples.R
man/str_glue.Rd
man/str_replace.Rd
tests/testthat/test-wrap.R
vignettes/from-base.Rmd
vignettes/regular-expressions.Rmd
vignettes/stringr.Rmd

Note: One `str_glue()` example still needs to use magrittr,
because this does not work with the base R placeholder:
```r
mtcars |> str_glue_data("{rownames(_)} has {hp} hp")
```

Use the base pipe, require R 4.1.0
