tidyverse/stringr

- NEWS.md
- R/replace.r
- tests/testthat/test-replace.r
> BUGFIX for fix_replacement

- .Rbuildignore
- README.Rmd
- README.md
- appveyor.yml
Tests on appvayor keep failing due to lack of `appveyor.yml`:
> Add appvayor.yml

- R/modifiers.r
Fixes https://github.com/tidyverse/stringr/issues/148.
> replaced is_bare_character() with coerce_to_bare_character()

- R/pad-trim.r
- tests/testthat/test-trunc.r
One-line change to function code, with two new tests to prevent regression.
Fixes #162.
> Allow str_trunc to pass through NA's in input.

- R/replace.r
Example was a bit long but it is because there were some identical lines. 
I deleted the duplicated example lines
> duplicated examples in str_replace

- NEWS.md
- R/trunc.R
- tests/testthat/test-trunc.r
Fixes #163.
Added a simple check and two minor tests.
> Throw error when asked to truncate to length shorter than ellipsis.

- vignettes/stringr.Rmd
Change was tested. No errors, warnings or notes.
> Fix typo 'length' s/b 'left' in vignette stringr.Rmd

- DESCRIPTION
- R/detect.r
- R/subset.R
- man/modifiers.Rd
- man/str_detect.Rd
- man/str_glue.Rd
- man/str_subset.Rd
- man/stringr-package.Rd
Includes update to roxygen2 6.1.0.
> Documentation: Establish link to grepl() and between str_which() and str_detect()

- R/c.r
- man/str_c.Rd
See issue #276, the initial explanation of what `str_c()` does is a little intimidating (or it was for a few folks in a class I taught recently). I would welcome any edits to what I've come up with...it is a hard thing to explain! If `str_collapse()` were a different function it may be easier to explain, but I get that `str_c()` is trying to be a drop-in replacement for `paste0()`.
> Add an alternative description for `str_c`

- vignettes/from-base.Rmd
> Fix typo in vignette

- tests/testthat/test-pad.r
changing expectation for test-pad so that it can fail
> fixing expectation #301

- R/data.R
- man/stringr-data.Rd
- man/stringr-package.Rd
`word` is a function, `words` is the dataset.
> Fix reference to words data

- R/flatten.R
- man/str_flatten.Rd
More stuff found while working on R Packages
> Add two words, one must-have, one nice-to-have

- NEWS.md
- R/split.R
- man/str_split.Rd
- tests/testthat/test-split.R
Reverts 67678a258b9bea70ece87f6d682265e281975da2. Fixes #469
> Pad str_split_fixed with ""

- R/detect.R
- man/str_detect.Rd
- man/str_starts.Rd
- man/str_subset.Rd
- man/str_which.Rd
> Improve `str_detect` documentation (#489)

- R/subset.R
- tests/testthat/test-subset.R
> str_subset to keep names if present

- R/glue.R
- man/str_glue.Rd
- tests/testthat/test-glue.R
> Add trim param to `str_glue()`

- vignettes/regular-expressions.Rmd
- vignettes/stringr.Rmd
> changed the chunk style of vignettes from curly brackets to hash pipes 

- NEWS.md
- R/view.R
- tests/testthat/_snaps/view.md
- tests/testthat/test-view.R
Returns a message instead of returning nothing which was the previous behavior. Existing snapshot updated.
Fixes #497
> Adds a message when an empty string is provided

- NEWS.md
- R/sub.R
- man/str_sub.Rd
- tests/testthat/_snaps/sub.md
- tests/testthat/test-sub.R
* Better documentation for `start` and `end`. Fixes #547
* Add test for empty strings
* Check `value` length and add test
> Polishing `str_sub()`
